### ISSUE TITLE
Broken for MAC

### ISSUE THREAD

**Issue by ldath** [anchore/homebrew-syft#1]
Hi currently this one is breaking brew:

```
$ brew readall
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/anchore/homebrew-syft/syft.rb
formulae require at least a URL
```

because of this:

```  
  if OS.mac?
  elsif OS.linux?
```

I just updated this manually on my laptop with this:

```
  if OS.mac?
    if Hardware::CPU.intel?
      url "https://github.com/anchore/syft/releases/download/v0.5.1/syft_0.5.1_darwin_amd64.dmg"
      sha256 "b9287e8b28eff94c84e518ccc99cc8d1438846c400b67ec886a82de641a3de76"
    end
  elsif OS.linux?
```
is there a reason that OS.mac is empty?

**Comment by wagoodman** [comment]
@ldath indeed, our last release generated an unexpected homebrew formulae, breaking our tap. We still need to fix the underlying problem with the release pipeline, but in the meantime we fixed the formulae manually: https://github.com/anchore/homebrew-syft/blob/master/syft.rb#L8-L16 .

Thanks for reporting!
