### ISSUE TITLE
Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by kkovaletp** [anchore/homebrew-syft#3]
When I've used brew today, I've got next warning:
`Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the anchore/syft tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/anchore/homebrew-syft/syft.rb:9`

**Comment by luhring** [comment]
Thanks! Just yesterday we also opened https://github.com/anchore/syft/issues/588 to track this.

cc: @wagoodman

**Comment by spiffcs** [comment]
Go releaser has updated where this is no longer a thing. Closing this issue
